### Withdraw all course detail name and version for reference

GET http://localhost:3002/coursedetail HTTP/1.1

### Withdraw data with specific id

GET http://localhost:3002/coursedetail/20 HTTP/1.1

### check if checkType() function correctly

GET http://localhost:3002/coursedetail/20/Software%20Quality%20Management/1/19/CS/SE HTTP/1.1


### Withdraw data with join data (Course)

GET http://localhost:3002/coursedetail/!/!/!/19 HTTP/1.1

### Withdraw bulk data with join data (Course.dept)

GET http://localhost:3002/coursedetail/!/!/!/!/TEST HTTP/1.1

### Withdraw non existing data

GET http://localhost:3002/coursedetail/50 HTTP/1.1

### Input invalid parameters

GET http://localhost:3002/coursedetail/g HTTP/1.1