# Generated by Django 3.2.5 on 2022-07-29 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asdasd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
    ]
